### ISSUE TITLE
error

### ISSUE THREAD

**Issue by snowdqdzq** [MCHDF/MCBOT#2]
![image](https://user-images.githubusercontent.com/52897962/102700074-700f5c00-424a-11eb-8ba0-a6701ff0a3c1.png)
 where is this

**Comment by MCHDF** [comment]
commit

**Comment by MCHDF** [comment]
I used a translator, so please understand even if it's incorrect.

It's the first time there's an issue here, so I'm not sure how to answer it, but I've given you a commitment, so please refer to it.
